version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Expo CLI
          command: npm install -g expo-cli
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build iOS App
          command: expo build:ios --no-wait
workflows:
  version: 2
  build:
    jobs:
      - build
